# Types of Matrices

## Transposed Matrix

A matrix in which the rows ad columns of $m \times n$-dimensional matrix $A$ are exchanged is Called A's tranposed matrix and represented by $A^T$

$$A_{ij} = A^T_{ji}$$


In [2]:
import numpy as np

In [3]:
A = np.array([
    [2, 4, 9],
    [3, 6, 7]
])
print(A)

[[2 4 9]
 [3 6 7]]


In [4]:
A.T

array([[2, 3],
       [4, 6],
       [9, 7]])

In [5]:
# Transpose of the transpose matrix becomes the original matrix
(A.T).T

array([[2, 4, 9],
       [3, 6, 7]])

In [6]:
B = np.random.randint(-10, 10, (3,3))
B

array([[ 6, -2, -6],
       [-8, -4, -8],
       [ 8, -9, -6]])

In [7]:
A @ B

array([[  52, -101,  -98],
       [  26,  -93, -108]])

In [8]:
# transpose of the matrix product between two matrices:
(A @ B).T == B.T @ A.T

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

## Square Matrix



In [9]:
A= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# extract diagonal vector
d = np.diag(A)

In [11]:
d

array([1, 5, 9])

In [15]:
# Trace of a matrix
np.trace(A)

15

## Identity Matrix

The identity matrix is a matrix in which the diagonal elements are all 1 and all other elements are 0

In [14]:
I = np.identity(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Diagonal Matrix

In [16]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

## Triangular Matrix
The triangular matrix can be divided into a lower triangular matrix and an upper triangular matrix based on the diagonal elements of the matrix.

In [19]:
x = np.random.randint(1, 9, 25).reshape((5,5))
x

array([[8, 8, 7, 6, 2],
       [5, 7, 1, 3, 1],
       [6, 5, 3, 6, 7],
       [7, 6, 4, 1, 8],
       [5, 2, 6, 6, 3]])

In [20]:
# Upper triangular Matrix
np.triu(x)

array([[8, 8, 7, 6, 2],
       [0, 7, 1, 3, 1],
       [0, 0, 3, 6, 7],
       [0, 0, 0, 1, 8],
       [0, 0, 0, 0, 3]])

In [21]:
# Lower triangular matrix
np.tril(x)

array([[8, 0, 0, 0, 0],
       [5, 7, 0, 0, 0],
       [6, 5, 3, 0, 0],
       [7, 6, 4, 1, 0],
       [5, 2, 6, 6, 3]])

In [24]:
np.triu(x, k=1)

array([[0, 8, 7, 6, 2],
       [0, 0, 1, 3, 1],
       [0, 0, 0, 6, 7],
       [0, 0, 0, 0, 8],
       [0, 0, 0, 0, 0]])

The triangular matrix has the following characteristics:

* The transposed matrix of the lower triangular matrix becomes the upper triangular matrix and vice versa

In [25]:
tu = np.triu(x)
tu

array([[8, 8, 7, 6, 2],
       [0, 7, 1, 3, 1],
       [0, 0, 3, 6, 7],
       [0, 0, 0, 1, 8],
       [0, 0, 0, 0, 3]])

In [26]:
tu.T

array([[8, 0, 0, 0, 0],
       [8, 7, 0, 0, 0],
       [7, 1, 3, 0, 0],
       [6, 3, 6, 1, 0],
       [2, 1, 7, 8, 3]])

* If the diagonal elements of the triangular matrix are all 0, it becomes an irreversible matrix.

## Symmetric Matrix

It is a square matrix that shows a symmetric relationship with respect to the main diagonal element.

In [29]:
N = 4
b = np.random.randint(0,100,size=(N,N))
b_symm = (b + b.T)/2
b_symm

array([[69. , 45.5, 31.5, 75.5],
       [45.5, 52. , 57.5, 52.5],
       [31.5, 57.5, 25. , 66.5],
       [75.5, 52.5, 66.5, 54. ]])

Or we can use numpy's triu(A) and tril(A) functions, to create an upper and lower triangular matrix based on matrix A.

In [31]:
x = np.random.randint(0, 100, (N,N))
A = np.triu(x) + np.triu(x).T
A

array([[162,  19,  83,  59],
       [ 19,  14,  76,  59],
       [ 83,  76, 102,  17],
       [ 59,  59,  17,   6]])

In [32]:
y = np.random.randint(0, 100, (N,N))
B = np.tril(y) + np.tril(y).T
B

array([[ 88,  93,  74,  85],
       [ 93, 112,  77,  66],
       [ 74,  77,  32,  63],
       [ 85,  66,  63,  72]])

* The two symmetric matrices A ± B are symmetric matrices.
* If A is a reversible (matrix having an inverse matrix) symmetric matrix, then $A^{-1}$ is also a symmetric matrix.

In [35]:
B_inv = np.linalg.inv(B)
B_inv

array([[-0.06421624,  0.01404752,  0.01273495,  0.05179087],
       [ 0.01404752,  0.01173654,  0.00954208, -0.03569168],
       [ 0.01273495,  0.00954208, -0.03550662,  0.00728707],
       [ 0.05179087, -0.03569168,  0.00728707, -0.02091192]])

In [45]:
np.around(np.abs(np.tril(B_inv) - np.triu(B_inv).T))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])